temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temp)
mydata <- read.table(unz(temp, "household_power_consumption.txt"), header=TRUE,sep=";",na.strings="?")
Dates <-as.Date(mydata$Date,"%d/%m/%Y")
data_for_plots <- subset(mydata$Global_active_power,Dates=="2007-2-1"| Dates =="2007-2-2")
png("plot1.png", width = 480, height = 480)
hist(data_for_plots,col="Red",main="Global Active Power",xlab = "Gloval Active Power (kilowatts)")
dev.off()
unlink(temp)
