temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temp)
mydata <- read.table(unz(temp, "household_power_consumption.txt"), header=TRUE,sep=";",na.strings="?")
Dates <-as.Date(mydata$Date,"%d/%m/%Y")
data_for_plots0 <- subset(mydata$Global_active_power,Dates=="2007-2-1"| Dates =="2007-2-2")
data_for_plots1 <- subset(mydata$Sub_metering_1,Dates=="2007-2-1"| Dates =="2007-2-2")
data_for_plots2 <- subset(mydata$Sub_metering_2,Dates=="2007-2-1"| Dates =="2007-2-2")
data_for_plots3 <- subset(mydata$Sub_metering_3,Dates=="2007-2-1"| Dates =="2007-2-2")
data_for_plots4 <- subset(mydata$Voltage,Dates=="2007-2-1"| Dates =="2007-2-2")
data_for_plots5 <- subset(mydata$Global_reactive_power,Dates=="2007-2-1"| Dates =="2007-2-2")
png("plot4.png", width = 480, height = 480)
par(mfrow=c(2,2))
plot(data_for_plots0,type="l",col="Black",ylab="Global Active Power (kilowatts))",xlab="",xaxt="n")
axis(1, at=c(0, 60*24, 2*60*24), labels=c("Thu", "Fri", "Sat"))
plot(data_for_plots4,type="l",col="Black",ylab="Voltage",xlab="datetime",xaxt="n")
axis(1, at=c(0, 60*24, 2*60*24), labels=c("Thu", "Fri", "Sat"))
plot(data_for_plots1,type="l",col="black",ylab="Energy sub metering",xlab="",xaxt="n")
lines(data_for_plots2,col="red")
lines(data_for_plots3,col="blue")
axis(1, at=c(0, 60*24, 2*60*24), labels=c("Thu", "Fri", "Sat"))
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=c(1,1,1),bty="n")
plot(data_for_plots5,type="l",col="Black",ylab="Global_reactive_power",xlab="datetime",xaxt="n")
axis(1, at=c(0, 60*24, 2*60*24), labels=c("Thu", "Fri", "Sat"))
dev.off()
unlink(temp)