temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temp)
mydata <- read.table(unz(temp, "household_power_consumption.txt"), header=TRUE,sep=";",na.strings="?")
Dates <-as.Date(mydata$Date,"%d/%m/%Y")
data_for_plots <- subset(mydata$Global_active_power,Dates=="2007-2-1"| Dates =="2007-2-2")
png("plot2.png", width = 480, height = 480)
plot(data_for_plots,type="l",col="Black",ylab="Global Active Power (kilowatts))",xlab="",xaxt="n")
axis(1, at=c(0, 60*24, 2*60*24), labels=c("Thu", "Fri", "Sat"))
dev.off()
unlink(temp)
