temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temp)
mydata <- read.table(unz(temp, "household_power_consumption.txt"), header=TRUE,sep=";",na.strings="?")
Dates <-as.Date(mydata$Date,"%d/%m/%Y")
data_for_plots1 <- subset(mydata$Sub_metering_1,Dates=="2007-2-1"| Dates =="2007-2-2")
data_for_plots2 <- subset(mydata$Sub_metering_2,Dates=="2007-2-1"| Dates =="2007-2-2")
data_for_plots3 <- subset(mydata$Sub_metering_3,Dates=="2007-2-1"| Dates =="2007-2-2")
png("plot3.png", width = 480, height = 480)
plot(data_for_plots1,type="l",col="black",ylab="Energy sub metering",xlab="",xaxt="n")
lines(data_for_plots2,col="red")
lines(data_for_plots3,col="blue")
axis(1, at=c(0, 60*24, 2*60*24), labels=c("Thu", "Fri", "Sat"))
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=c(1,1,1))
dev.off()
unlink(temp)
